version: "3.9"
services:
    chutney-server:
        container_name: chutney-server
        image: ghcr.io/chutney-testing/chutney/chutney-server:latest
        restart: unless-stopped
        ports:
            - "8081:8443"
        volumes:
            - ./chutney_environments:/.chutney
